# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true
  config.hostmanager.include_offline = true
  config.hostmanager.ignore_private_ip = false

  # Workaround to avoid virtualbox captures microphone all the time
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.memory = "1024"
  end

  # Server machine to host samba share
  config.vm.define "samba1" do |samba1|
    samba1.vm.hostname = "samba1"
    samba1.vm.network "private_network", ip: "10.0.1.10"

    samba1.vm.provision "shell", path: "scripts/install.sh", privileged: true
    samba1.vm.provision "file", source: "~/.ssh/vagrant_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    samba1.vm.provision "shell", "inline": <<-SHELL
      cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  # Defines primary server to ssh into by default.
  # When using the lab this is the main server to connect to perform administrative tasks
  config.vm.define "client1", primary: true do |client1|
    client1.vm.hostname = "client1"
    client1.vm.network "private_network", ip: "10.0.1.11"

    client1.vm.provision "shell", path: "scripts/install.sh", privileged: true
    client1.vm.provision "file", source: "~/.ssh/vagrant_rsa", destination: "~/.ssh/id_rsa"

    client1.vm.provider "virtualbox" do |vb|
      unless File.exist?("./disk2.vdi")
        vb.customize ["storagectl", :id, "--name", "SCSI", "--add", "scsi"]
      end
      unless File.exist?("./disk2.vdi")
        vb.customize ["createhd", "--filename", "./disk2.vdi", "--variant", "Fixed", "--size", 5 * 1024]
      end
      unless File.exist?("./disk3.vdi")
        vb.customize ["createhd", "--filename", "./disk3.vdi", "--variant", "Fixed", "--size", 10 * 1024]
      end

      vb.customize ["storageattach", :id,
                    "--storagectl", "SCSI",
                    "--port", 1,
                    "--device", 0,
                    "--type", "hdd",
                    "--medium", "./disk2.vdi"]

      vb.customize ["storageattach", :id,
                    "--storagectl", "SCSI",
                    "--port", 2,
                    "--device", 0,
                    "--type", "hdd",
                    "--medium", "./disk3.vdi"]
    end
  end

end
