# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.memory = "2048"
  end

  config.vm.define "server1" do |server1|
    server1.vm.hostname = "server1"
    server1.vm.network "private_network", ip: "10.0.1.10"


    server1.vm.provider "virtualbox" do |vb|
      unless File.exist?("./disk2.vdi")
        vb.customize ["createhd", "--filename", "./disk2.vdi", "--variant", "Fixed", "--size", 5 * 1024]
      end

      vb.customize ["storageattach", :id, "--storagectl", "IDE", "--port", 1, "--device", 0, "--type", "hdd", "--medium", "./disk2.vdi"]
    end

  end
end
