# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true
  config.hostmanager.include_offline = true
  config.hostmanager.ignore_private_ip = false
  
  # Workaround to avoid virtualbox captures microphone all the time
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.memory = "512"
  end

  config.vm.provision "shell", path: "scripts/install.sh", privileged: true

  config.vm.define "ns1" do |ns1|

    ns1.vm.hostname = "ns1"
    ns1.vm.network "private_network", ip: "10.0.1.10"

    ns1.vm.provision "file", source: "~/.ssh/vagrant_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    ns1.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "ns2" do |ns2|

    ns2.vm.hostname = "ns2"
    ns2.vm.network "private_network", ip: "10.0.1.20"

    ns2.vm.provision "file", source: "~/.ssh/vagrant_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    ns2.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "apache1" do |apache1|

    apache1.vm.hostname = "apache1"
    apache1.vm.network "private_network", ip: "10.0.1.12"

    apache1.vm.provision "file", source: "~/.ssh/vagrant_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    apache1.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
      yum install -q -y httpd
      systemctl enable httpd --now 2>&1
      echo "This content is from the apache server! Congratulations!" > /var/www/html/index.html

      firewall-cmd --list-services | grep http
      if [ $? -ne 0 ]; then
        echo "Opening port 80 on firewalld"
        firewall-cmd --permanent --add-service http
        firewall-cmd --reload 
      fi
    SHELL
  end
  
  # Defines the primary server to ssh into by default.
  # When using the lab, this is the main server to perform administrative tasks
  config.vm.define "client1", primary: true do |client1|

    client1.vm.hostname = "client1"
    client1.vm.network "private_network", ip: "10.0.1.11"
    client1.hostmanager.aliases = %w(client1.localdomain client1.localnet)

    client1.vm.provision "file", source: "~/.ssh/vagrant_rsa", destination: "~/.ssh/id_rsa"
  end
end
