# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true
  config.hostmanager.include_offline = true
  config.hostmanager.ignore_private_ip = false
  
  # Workaround to avoid virtualbox captures microphone all the time
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.memory = "1024"
  end

  config.vm.provision "shell", path: "scripts/install.sh", privileged: true
  
  # Defines the primary server to ssh into by defaul.
  # When using the lab, this is the main server to commet to perform administrative tasks
  config.vm.define "server1", primary: true do |server1|

    server1.vm.hostname = "server1"
    server1.vm.network "private_network", ip: "10.0.1.10"
    server1.hostmanager.aliases = %w(server1.localdomain server1.localnet)

    server1.vm.provision "file", source: "~/.ssh/vagrant_rsa", destination: "~/.ssh/id_rsa"
  end

  config.vm.define "server2" do |server2|

    server2.vm.hostname = "server2"
    server2.vm.network "private_network", ip: "10.0.1.20"

    server2.vm.provision "file", source: "~/.ssh/vagrant_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    server2.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "server3" do |server3|

    server3.vm.hostname = "server3"
    server3.vm.network "private_network", ip: "10.0.1.30"

    server3.vm.provision "file", source: "~/.ssh/vagrant_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    server3.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
end
