# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.box = "centos/7"
  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true
  config.hostmanager.include_offline = true
  config.hostmanager.ignore_private_ip = false

  # Workaround to avoid virtualbox captures microphone all the time
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--audio", "none"]

    # By default servers will have 512MB of memory.
    # If required by the hosted services the larger memory amount will be specified on every instance
    vb.memory = "512"
  end

  # Run the standard installation script. This is going to be the same for all servers
  config.vm.provision "shell", path: "scripts/install.sh", privileged: true

  # Uncomment the line below to also attach the servers to the bridged network. 
  # Be aware that when running the `vagrant up` or `vagrant reload` commands
  # you'll need to manually select which host interface to use for the bridged interface.
  #
  # config.vm.network "public_network"

  # ns1 can be used as primary name server in an authoritative NS configuration
  config.vm.define "ns1" do |ns1|
    ns1.vm.hostname = "ns-node-1"
    ns1.vm.network "private_network", ip: "10.0.1.40"

    ns1.vm.provision "file", source: "~/.ssh/vagrant_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    ns1.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  # ns2 can be used as secondary name server in an authoritative NS configuration
  config.vm.define "ns2" do |ns2|
    ns2.vm.hostname = "ns-node-2"
    ns2.vm.network "private_network", ip: "10.0.1.41"

    ns2.vm.provision "file", source: "~/.ssh/vagrant_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    ns2.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  # recns1 has been introduced to provide a separate server to use as recursive (caching) DNS server
  config.vm.define "recns1" do |recns1|
    recns1.vm.hostname = "ns-node-rec"
    recns1.vm.network "private_network", ip: "10.0.1.49"

    recns1.vm.provision "file", source: "~/.ssh/vagrant_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    recns1.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "proxy1" do |proxy1|
    proxy1.vm.hostname = "proxy-node-1"
    proxy1.vm.network "private_network", ip: "10.0.1.60"

    proxy1.vm.provision "file", source: "~/.ssh/vagrant_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    proxy1.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "mail1" do |mail1|
    mail1.vm.hostname = "mail-node-1"
    mail1.vm.network "private_network", ip: "10.0.1.50"

    mail1.vm.provision "file", source: "~/.ssh/vagrant_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    mail1.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  config.vm.define "apache1" do |apache1|
    apache1.vm.hostname = "apache-node-1"
    apache1.vm.network "private_network", ip: "10.0.1.30"

    apache1.vm.provision "file", source: "~/.ssh/vagrant_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    apache1.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
      yum install -q -y httpd
      systemctl enable httpd --now 2>&1
      echo "This content is from the apache1 server! Congratulations!" > /var/www/html/index.html

      firewall-cmd --list-services | grep http
      if [ $? -ne 0 ]; then
        echo "Opening port 80 on firewalld"
        firewall-cmd --permanent --add-service http
        firewall-cmd --reload 
      fi
    SHELL
  end

  # Server machine to host samba share
  config.vm.define "samba1" do |samba1|
    samba1.vm.hostname = "samba-node-1"
    samba1.vm.network "private_network", ip: "10.0.1.20"

    samba1.vm.provision "shell", path: "scripts/install.sh", privileged: true
    samba1.vm.provision "file", source: "~/.ssh/vagrant_rsa.pub", destination: "~/.ssh/id_rsa.pub"
    samba1.vm.provision "shell", "inline": <<-SHELL
      cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    SHELL

    # Additional disks added for the samba1 machine.
    # The purpose of these disks here is to practice configuring a samba share over a RAID array for data redundancy.
    samba1.vm.provider "virtualbox" do |vb|
      unless File.exist?(".vagrant/samba1_disk2.vdi")
        vb.customize ["storagectl", :id, "--name", "SCSI", "--add", "scsi"]
      end
      unless File.exist?(".vagrant/samba1_disk2.vdi")
        vb.customize ["createhd", "--filename", ".vagrant/samba1_disk2.vdi", "--variant", "Fixed", "--size", 2 * 1024]
      end
      unless File.exist?(".vagrant/samba1_disk3.vdi")
        vb.customize ["createhd", "--filename", ".vagrant/samba1_disk3.vdi", "--variant", "Fixed", "--size", 2 * 1024]
      end
      unless File.exist?(".vagrant/samba1_disk4.vdi")
        vb.customize ["createhd", "--filename", ".vagrant/samba1_disk4.vdi", "--variant", "Fixed", "--size", 2 * 1024]
      end

      vb.customize ["storageattach", :id,
                    "--storagectl", "SCSI",
                    "--port", 1,
                    "--device", 0,
                    "--type", "hdd",
                    "--medium", ".vagrant/samba1_disk2.vdi"]

      vb.customize ["storageattach", :id,
                    "--storagectl", "SCSI",
                    "--port", 2,
                    "--device", 0,
                    "--type", "hdd",
                    "--medium", ".vagrant/samba1_disk3.vdi"]
      vb.customize ["storageattach", :id,
                    "--storagectl", "SCSI",
                    "--port", 3,
                    "--device", 0,
                    "--type", "hdd",
                    "--medium", ".vagrant/samba1_disk4.vdi"]
    end
  end

  # Defines primary server to ssh into by default.
  # When using the lab this is the main server to connect to perform administrative tasks
  config.vm.define "node1", primary: true do |node1|
    node1.vm.hostname = "node-1"
    node1.vm.network "private_network", ip: "10.0.1.11"

    node1.vm.provision "shell", path: "scripts/install.sh", privileged: true
    node1.vm.provision "file", source: "~/.ssh/vagrant_rsa", destination: "~/.ssh/id_rsa"
    node1.vm.provision "file", source: "~/.ssh/vagrant_rsa.pub", destination: "~/.ssh/id_rsa.pub"

    node1.vm.provider "virtualbox" do |vb|
      unless File.exist?(".vagrant/node1_disk2.vdi")
        vb.customize ["storagectl", :id, "--name", "SCSI", "--add", "scsi"]
      end
      unless File.exist?(".vagrant/node1_disk2.vdi")
        vb.customize ["createhd", "--filename", ".vagrant/node1_disk2.vdi", "--variant", "Fixed", "--size", 5 * 1024]
      end
      unless File.exist?(".vagrant/node1_disk3.vdi")
        vb.customize ["createhd", "--filename", ".vagrant/node1_disk3.vdi", "--variant", "Fixed", "--size", 10 * 1024]
      end
      unless File.exist?(".vagrant/node1_disk4.vdi")
        vb.customize ["createhd", "--filename", ".vagrant/node1_disk4.vdi", "--variant", "Fixed", "--size", 2 * 1024]
      end
      unless File.exist?(".vagrant/node1_disk5.vdi")
        vb.customize ["createhd", "--filename", ".vagrant/node1_disk5.vdi", "--variant", "Fixed", "--size", 2 * 1024]
      end
      unless File.exist?(".vagrant/node1_disk6.vdi")
        vb.customize ["createhd", "--filename", ".vagrant/node1_disk6.vdi", "--variant", "Fixed", "--size", 2 * 1024]
      end

      vb.customize ["storageattach", :id,
                    "--storagectl", "SCSI",
                    "--port", 1,
                    "--device", 0,
                    "--type", "hdd",
                    "--medium", ".vagrant/node1_disk2.vdi"]

      vb.customize ["storageattach", :id,
                    "--storagectl", "SCSI",
                    "--port", 2,
                    "--device", 0,
                    "--type", "hdd",
                    "--medium", ".vagrant/node1_disk3.vdi"]
      vb.customize ["storageattach", :id,
                    "--storagectl", "SCSI",
                    "--port", 3,
                    "--device", 0,
                    "--type", "hdd",
                    "--medium", ".vagrant/node1_disk4.vdi"]
      vb.customize ["storageattach", :id,
                    "--storagectl", "SCSI",
                    "--port", 4,
                    "--device", 0,
                    "--type", "hdd",
                    "--medium", ".vagrant/node1_disk5.vdi"]
      vb.customize ["storageattach", :id,
                    "--storagectl", "SCSI",
                    "--port", 5,
                    "--device", 0,
                    "--type", "hdd",
                    "--medium", ".vagrant/node1_disk6.vdi"]
    end
  end
end
